version: "3.7"
services:
  front:
    build:
      context: .
      dockerfile: front.Dockerfile
    ports:
      - "8080:80"
  api:
    build: .
    container_name: FastChat-api
    ports:
      - "${APP_PORT:-10000}:10000"
    environment:
      REDIS_IP: redis
      REDIS_PORT: 6379
    volumes:
      - ".:/srv"
    networks:
      - internal
    depends_on:
      - "redis"
    hostname: api
  redis:
    image: redis:7.0.2
    container_name: FastChat-redis
    ports:
      - 6379:6379
    networks:
      - internal
networks:
  internal:
    external: false
